ONOS:
    general:
        onosbench_username: 'root'
        onosbench_password: 'root'
        onoscli_username: 'root'
        onoscli_password: 'root'
        runtimeout: 300
    environment:
        OCT: '189.42.8.99'
        OC1: '189.42.8.101'
        OC2: '189.42.8.102'
        OC3: '189.42.8.103'
        OCN: '189.42.8.104'
        OCN2: '189.42.8.105'
results:
    test_db_url: http://213.77.62.197